#!/usr/bin/python

import psycopg2

print(dir(pyscopg2))
#conn = psycopg2.connect(dbname='zipcode', user ='postgres', host='localhost', port=5432, password='');

#except: 
#  print("I am unable to connect to the databse");
  
